server:
  port: 8848
  tomcat:
    basedir: logs
    connection-timeout: 5000
    max-connections: 2000
    max-threads: 2000
db:
  num: 1
  user: root
  password: Beanmr@0521
  url:
    0: jdbc:mysql://172.18.1.217:3306/ovmsx_config?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


nacos:
  core:
    auth:
      system.type: nacos
      default.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql
  security:
    enabled: true
  mvc:
    async:
      request-timeout: 5000

useAddressServer: true

